const SET_THEME = 'SET_THEME'
const SET_VIEWHEIGHT = 'SET_VIEWHEIGHT'
const SET_VIEWWIDTH = 'SET_VIEWWIDTH'
const SET_VIEWZOOM = 'SET_VIEWZOOM'

export { SET_THEME, SET_VIEWHEIGHT, SET_VIEWWIDTH, SET_VIEWZOOM }
